name: SyntaxKit
settings:
  LINT_MODE: ${LINT_MODE}
packages:
  SyntaxKit:
    path: .
  SKSampleMacro:
    path: Macros/SKSampleMacro
  Options:
    path: Macros/Options
aggregateTargets:
  Lint:
    buildScripts:
      - path: Scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
    schemes: {}
